import { test, expect } from './fixtures';

test('tags connect passages and story records, survive rename and reload, and expose backlinks', async ({ page, projectId, request }, testInfo) => {
  const created = await request.post(`/api/projects/${projectId}/canon/entities`, { data: { type: 'character', name: 'Mara', aliases: ['The Keeper'] } });
  expect(created.ok()).toBeTruthy();
  const draft = page.locator('.pane-editor textarea.draft');
  await draft.fill('Mara carried the winter lantern.\nThe harbour held its breath.');
  await draft.evaluate((el: HTMLTextAreaElement) => { el.focus(); el.setSelectionRange(0, 4); });
  await page.getByRole('button', { name: 'Tag or link selection', exact: true }).click();
  const panel = page.getByRole('dialog', { name: 'Tags and connections', exact: true });
  await panel.getByLabel('New tag', { exact: true }).fill('Winter');
  await panel.getByRole('button', { name: 'Create and attach tag', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Remove tag Winter', exact: true })).toBeVisible();
  await panel.getByLabel('Find story record', { exact: true }).fill('Keeper');
  await panel.getByRole('button', { name: 'Link Character: Mara', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Remove link Mara', exact: true })).toBeVisible();
  await panel.getByRole('button', { name: 'Inspect Character: Mara', exact: true }).click();
  await panel.getByLabel('Existing tag', { exact: true }).selectOption({ label: 'Winter' });
  await panel.getByRole('button', { name: 'Attach tag', exact: true }).click();
  await expect(panel.getByRole('button', { name: /Go to passage in Chapter One/ })).toBeVisible();
  await panel.getByRole('button', { name: 'Filter tag Winter', exact: true }).click();
  await panel.getByLabel('Rename tag', { exact: true }).fill('Winter lantern');
  await panel.getByRole('button', { name: 'Save tag name', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Filter tag Winter lantern', exact: true })).toBeVisible();
  await panel.getByLabel('Record type', { exact: true }).selectOption('canon');
  await expect(panel.getByRole('button', { name: 'Inspect Character: Mara', exact: true })).toBeVisible();
  await expect(panel.getByRole('button', { name: 'Inspect Document: Chapter One', exact: true })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath('connections-desktop.png') });
  await panel.press('Escape');
  await page.reload();
  await page.getByRole('button', { name: 'Open connections', exact: true }).click();
  await panel.getByRole('button', { name: 'Filter tag Winter lantern', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Inspect Character: Mara', exact: true })).toBeVisible();
  await expect(panel.getByRole('button', { name: 'Inspect Document: Chapter One', exact: true })).toBeVisible();
  await expect(draft).toHaveValue('Mara carried the winter lantern.\nThe harbour held its breath.');
});

test('connection controls remain reachable in phone focus', async ({ page, projectId }, testInfo) => {
  expect(projectId).toBeTruthy();
  await page.setViewportSize({ width: 390, height: 844 });
  const draft = page.locator('.pane-editor textarea.draft');
  await draft.fill('Mara keeps watch.');
  await page.getByRole('button', { name: 'Focus writing', exact: true }).click();
  await draft.evaluate((el: HTMLTextAreaElement) => { el.focus(); el.setSelectionRange(4, 4); });
  await page.keyboard.type('!#');
  const panel = page.getByRole('dialog', { name: 'Tags and connections', exact: true });
  await expect(panel).toBeInViewport();
  await panel.getByLabel('New tag', { exact: true }).fill('Watch');
  await panel.getByRole('button', { name: 'Create and attach tag', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Remove tag Watch', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await page.screenshot({ path: testInfo.outputPath('connections-phone.png') });
  await panel.press('Escape');
  await expect(draft).toHaveValue('Mara keeps watch.');
  await expect(page.getByRole('button', { name: 'Exit writing focus', exact: true })).toBeVisible();
});

test('bang-hash links a selected passage in quiet focus without leaving command tokens in prose', async ({ page, projectId, request }) => {
  await request.post(`/api/projects/${projectId}/canon/entities`, { data: { type: 'character', name: 'Mara' } });
  const draft = page.locator('.pane-editor textarea.draft');
  await draft.fill('Mara watched the tide.');
  await page.getByRole('button', { name: 'Focus writing', exact: true }).click();
  await page.getByRole('button', { name: 'Hide writing controls', exact: true }).click();
  await draft.evaluate((el: HTMLTextAreaElement) => { el.focus(); el.setSelectionRange(0, 4); });
  await page.keyboard.type('!#');
  const panel = page.getByRole('dialog', { name: 'Tags and connections', exact: true });
  await expect(panel).toBeVisible();
  await expect(draft).toHaveValue('Mara watched the tide.');
  await panel.getByLabel('Find story record', { exact: true }).fill('Mara');
  await panel.getByRole('button', { name: 'Link Character: Mara', exact: true }).click();
  await panel.getByRole('button', { name: 'Open Character: Mara', exact: true }).click();
  const card = page.getByRole('dialog', { name: 'Revise Mara', exact: true });
  await expect(card).toBeVisible();
  await card.getByPlaceholder('Character name').fill('Mara revised');
  await card.press('Escape');
  await expect(draft).toBeFocused();
  await expect(page.getByRole('button', { name: 'Show writing controls', exact: true })).toBeVisible();
  await expect(draft).toHaveValue('Mara watched the tide.');
  await draft.press('Escape');
  await expect(page.getByRole('button', { name: 'Focus writing', exact: true })).toBeVisible();
});

test('passage navigation relocates surviving context and refuses changed context', async ({ page, projectId, request }) => {
  const { project } = await (await request.get(`/api/projects/${projectId}`)).json();
  const docId = project.documents.find((doc: { kind: string }) => doc.kind === 'manuscript').id;
  const draft = page.locator('.pane-editor textarea.draft');
  const original = 'Mara carried the lantern to the harbour.';
  await draft.fill(original);
  await draft.evaluate((el: HTMLTextAreaElement) => { el.focus(); el.setSelectionRange(0, 4); });
  await page.getByRole('button', { name: 'Tag or link selection', exact: true }).click();
  const panel = page.getByRole('dialog', { name: 'Tags and connections', exact: true });
  await panel.getByLabel('New tag', { exact: true }).fill('Lantern');
  await panel.getByRole('button', { name: 'Create and attach tag', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Remove tag Lantern', exact: true })).toBeVisible();
  await panel.press('Escape');
  const prefix = 'An earlier scene ends.\n';
  await draft.fill(prefix + original);
  await page.getByRole('button', { name: 'Open connections', exact: true }).click();
  await panel.getByRole('button', { name: 'Filter tag Lantern', exact: true }).click();
  await panel.getByRole('button', { name: 'Go to passage in Chapter One', exact: true }).click();
  await expect(panel).toBeHidden();
  await expect(draft).toBeFocused();
  expect(await draft.evaluate((el: HTMLTextAreaElement) => [el.selectionStart, el.selectionEnd])).toEqual([prefix.length, prefix.length + 4]);
  await draft.fill('Mara carried a different lantern.');
  await page.getByRole('button', { name: 'Open connections', exact: true }).click();
  await panel.getByRole('button', { name: 'Filter tag Lantern', exact: true }).click();
  await panel.getByRole('button', { name: 'Go to passage in Chapter One', exact: true }).click();
  await expect(panel.getByRole('alert')).toContainText('nearby context has changed');
  await expect(draft).toHaveValue('Mara carried a different lantern.');
  expect((await (await request.get(`/api/projects/${projectId}/connections`)).json()).connections.attachments[0].target.id).toBe(docId);
  await panel.getByRole('button', { name: 'Remove passage connection', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Go to passage in Chapter One', exact: true })).toHaveCount(0);
  await expect(panel.getByRole('button', { name: 'Filter tag Lantern', exact: true })).toBeVisible();
});

test('record connections form a nested focus layer and Escape returns through the same unsaved card', async ({ page, projectId, request }) => {
  await request.post(`/api/projects/${projectId}/canon/entities`, { data: { type: 'character', name: 'Layer keeper' } });
  await page.getByRole('button', { name: 'Focus writing', exact: true }).click();
  await page.getByRole('button', { name: 'Open story cards', exact: true }).click();
  await page.getByRole('button', { name: 'Character: Layer keeper', exact: true }).click();
  const card = page.getByRole('dialog', { name: 'Revise Layer keeper', exact: true });
  await card.getByPlaceholder('Character name').fill('Unsaved keeper');
  await card.getByRole('button', { name: 'Tags and links', exact: true }).click();
  const panel = page.getByRole('dialog', { name: 'Tags and connections', exact: true });
  await expect(panel).toBeVisible();
  await panel.press('Escape');
  await expect(card).toBeVisible();
  await expect(card.getByPlaceholder('Character name')).toHaveValue('Unsaved keeper');
  await card.press('Escape');
  await expect(page.locator('.pane-editor textarea.draft')).toBeFocused();
  await expect(page.getByRole('button', { name: 'Exit writing focus', exact: true })).toBeVisible();
});
