import { test, expect } from './fixtures';

test('parked tools share Tabs and Stack views without losing drafts or original layout', async ({ page, projectId }, testInfo) => {
  const manuscriptPane = page.locator('.pane-editor');
  const muse = page.getByPlaceholder('Ask Muse…');
  const notes = page.locator('.pane-notes').getByRole('textbox');
  await expect(muse).toBeVisible();
  await muse.fill('A question held in the drawer.');
  await notes.fill(`Drawer notes ${projectId}`);
  const before = await manuscriptPane.boundingBox();
  await page.locator('.pane-agent').getByRole('button', { name: 'Minimize', exact: true }).click();
  await page.locator('.pane-notes').getByRole('button', { name: 'Minimize', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Open tool drawer', exact: true })).toBeVisible();
  await expect(muse).toBeHidden();
  expect((await manuscriptPane.boundingBox())!.width).toBeGreaterThan(before!.width + 250);
  expect((await manuscriptPane.boundingBox())!.height).toBeGreaterThan(before!.height + 100);
  await page.getByRole('button', { name: 'Open tool drawer', exact: true }).click();
  const drawer = page.getByRole('region', { name: 'Parked workspace tools', exact: true });
  await drawer.getByRole('tab', { name: 'Muse', exact: true }).click();
  await expect(muse).toHaveValue('A question held in the drawer.');
  await expect(muse).toBeVisible();
  await drawer.getByRole('tab', { name: 'Scratchpad', exact: true }).click();
  await expect(muse).toBeHidden();
  await expect(notes).toHaveValue(`Drawer notes ${projectId}`);
  await drawer.getByRole('button', { name: 'Stack', exact: true }).click();
  await expect(muse).toBeVisible();
  await expect(notes).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('tool-drawer-stack.png'), animations: 'disabled' });
  await muse.focus();
  await page.keyboard.press('Escape');
  await expect(drawer).toBeHidden();
  await expect(page.getByRole('button', { name: 'Open tool drawer', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Open tool drawer', exact: true }).click();
  await drawer.getByRole('button', { name: 'Restore Muse to workspace', exact: true }).click();
  await drawer.getByRole('button', { name: 'Restore Scratchpad to workspace', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Open tool drawer', exact: true })).toHaveCount(0);
  await expect(muse).toHaveValue('A question held in the drawer.');
  await expect(notes).toHaveValue(`Drawer notes ${projectId}`);
  expect(await manuscriptPane.boundingBox()).toEqual(before);
});

test('phone drawer supports keyboard tabs and remembers Stack for this workspace only', async ({ page, projectId }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  for (const type of ['agent', 'notes']) await page.locator(`.pane-${type}`).getByRole('button', { name: 'Minimize', exact: true }).click();
  await page.getByRole('button', { name: 'Open tool drawer', exact: true }).click();
  const drawer = page.getByRole('region', { name: 'Parked workspace tools', exact: true });
  await drawer.getByRole('tab', { name: 'Muse', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  await expect(drawer.getByRole('tab', { name: 'Scratchpad', exact: true })).toBeFocused();
  await expect(drawer.getByRole('tabpanel', { name: 'Scratchpad', exact: true })).toBeVisible();
  await drawer.getByRole('button', { name: 'Stack', exact: true }).click();
  await expect(drawer.getByRole('button', { name: 'Close tool drawer', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await page.screenshot({ path: testInfo.outputPath('tool-drawer-phone.png'), animations: 'disabled' });
  await page.reload();
  await page.locator('.pane-agent').getByRole('button', { name: 'Minimize', exact: true }).click();
  await page.getByRole('button', { name: 'Open tool drawer', exact: true }).click();
  await expect(drawer.getByRole('button', { name: 'Stack', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await drawer.getByRole('button', { name: 'Close tool drawer', exact: true }).click();
  await page.getByRole('button', { name: 'Planning', exact: true }).click();
  await page.locator('.pane-agent').getByRole('button', { name: 'Minimize', exact: true }).click();
  await page.getByRole('button', { name: 'Open tool drawer', exact: true }).click();
  await expect(drawer.getByRole('button', { name: 'Tabs', exact: true })).toHaveAttribute('aria-pressed', 'true');
});

test('a parked manuscript can focus and return to the open drawer on Escape', async ({ page, projectId }) => {
  const manuscript = page.locator('.pane-editor').getByPlaceholder('Start writing your story…');
  await expect(manuscript).toHaveValue(/Chapter One/);
  const original = await manuscript.inputValue();
  await page.locator('.pane-editor').getByRole('button', { name: 'Minimize', exact: true }).click();
  await page.getByRole('button', { name: 'Open tool drawer', exact: true }).click();
  await page.getByRole('button', { name: 'Focus writing', exact: true }).click();
  await expect(manuscript).toBeVisible();
  await expect(manuscript).toBeFocused();
  expect((await page.locator('.pane-editor').boundingBox())!.width).toBeGreaterThan(page.viewportSize()!.width - 24);
  await manuscript.fill(`${original}\nWritten from a parked page.`);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('region', { name: 'Parked workspace tools', exact: true })).toBeVisible();
  await expect(manuscript).toHaveValue(`${original}\nWritten from a parked page.`);
  await expect(manuscript).toBeFocused();
  await expect(page.getByRole('button', { name: 'Restore Chapter One to workspace', exact: true })).toBeVisible();
});
